### ISSUE TITLE
Capture containers outputs into separate files

### ISSUE THREAD

**Issue by dstepanov** [avast/gradle-docker-compose-plugin#122]
It would be nice if there was equivalent of `captureContainersOutputToFile` which would capture log output of separate containers into separate log files:

containerNameX.log
containerNameY.log

**Comment by augi** [comment]
Great news! It took less than one year and this feature is available in `0.8.12`! 😄 

There is a new option (`captureContainersOutputToFiles`) which specifies directory where log files are created for each service.

So the logging is not per-container but per-service (because it's how `docker-compose logs` command works). Hope it's ok for you.
