### ISSUE TITLE
Question about concurrent gradle builds in jenkins

### ISSUE THREAD

**Issue by avillev** [avast/gradle-docker-compose-plugin#140]
This is more a question than an issue.

When a project runs its integration tests using your gradle plugin (which is amazing :) ) on jenkins, concurrent jobs on the same node/slave often have problems (stopping other jobs docker containers for example).

I am wondering what configuration/guidelines you would use to allow concurrent executions with this use case ?

**Comment by augi** [comment]
IMHO the core of your problems is that `Docker Compose project name` is automatically derived from actual directory name, see [-p switch here](https://docs.docker.com/compose/reference/overview/).

This `project name` is later used as prefix when naming containers. E.g. if your `docker-compose.yml` file is in directory named `myproject` and it defines `pgsql` service then the container is named `myproject_pgsql_1` (the suffix `_1` is appended because services can be scaled).

So if Jenkins uses the same directory name for more projects then conflicts are possible.

Unfortunately, I have just little experience with Jenkins - we use TeamCity. And the TeamCity creates for each _build_ a new directory with unique name (a hash).

This Gradle plugins allows to set custom `project name`:
```gradle
dockerCompose {
  projectName = 'nameYouWant'
}
```

So my suggestion is to set a random `projectName`. If you don't want to set a random name for local development, you can check e.g. [JENKINS_URL](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-belowJenkinsSetEnvironmentVariables) environment variable.

**Comment by augi** [comment]
Maybe to clarify it more - if you have projects structured like this:
```
/usr/project1/tests/docker-compose.yaml
/usr/project2/tests/docker-compose.yaml
```
The `Docker Compose project name` will be `tests` for both projects.

**Comment by avillev** [comment]
Thank you.
That would work in some cases but if two projects, or the same project executed twice, are using the same port, wouldn't it generate a binding port conflict ?
Two Mysql containers or something like that.
