### ISSUE TITLE
Add option to ignore composeUp failures

### ISSUE THREAD

**Issue by dmsergeevp44** [avast/gradle-docker-compose-plugin#155]
I think it would make sense to add a configuration option to ignore compose up failures. 
Say we have 2 services, they all need one particular service, say kafka. Currently I won't be able to start them both because the second one will fail to start the kafka container. 
It would be nice if this could be ignored and an application be allowed to start

**Comment by augi** [comment]
Hi, I'm not fully sure if I understand your suggestion :( Could you please describe your use-case in more detail? Thanks!

**Comment by dmsergeevp44** [comment]
Sorry for not being clear.

The goal is to allow the application to start even though `docker-compose up` might not start all containers successfully.

The use case goes as follows --
We have 2 spring boot services that both depend on Apache Kafka running, so naturally `docker-compose.yml` for both services includes kafka. We have it set so that when you run bootRun docker-compose gradle plugin will also start the services listed in `docker-compose.yml`. The problem comes from the fact that these 2 services sometimes need to be running at the same time and both share the same Kafka broker (so dynamic port mapping is not an option here). Currently the plugin will only start one service and fail on the other because Kafka is already running as a result of running the first service.

I hope this clarifies it

**Comment by augi** [comment]
Ah, I got it - you have two separated `docker-compose.yml` files.

My suggestion for your use-case is to have one `docker-compose.yml` file for the situation when you want to execute two services that share single Kafka. If your original files are complicated, you could use the _include_ feature.

I don't want to add this _feature_ to the plugin because it's not just about ignoring the exit-code from the `up` command - the plugin performs various health checks and they would have to be changed as well. And in general, I don't think that errors ignoring is the best pattern, sorry.
