### ISSUE TITLE
docker-compose up fails on openjdk 11

### ISSUE THREAD

**Issue by knrybarczyk** [avast/gradle-docker-compose-plugin#203]
First of all thanks a lot for this great plugin and for all your contribution @augi 

I've started to notice an issue when I switched to openjdk-11 in the dockerfile of our project. 
Everything works fine with this: 
`FROM openjdk:10-jre-slim-sid`
but as soon as I update it to:
`FROM openjdk:11-jre-slim-sid`

then compose-up of this guy fails with: 
`These ports of service XYZ are declared as exposed but cannot be found in NetworkSettings: 8080`

This happens both locally on my MacOS machine and on CircleCI on Ubuntu 16.04 machine. The port obviously is not taken by anything else. I've checked this locally trying to see if anyone was listening on this port. Have you ever seen this before?

**Comment by augi** [comment]
Hello, thank you for reporting your issue!

Please read the error message carefully: `These ports of service XYZ are declared as exposed but cannot be found in NetworkSettings: 8080`

The problem is NOT that the port is taken by any other application. The problem is an inconsistency of `docker inspect` command output.

BUT! I'm not able to find the mentioned error message in current source code, so my bet is that your are using an old version of the plugin. So please just try to update the plugin version and it should help.

Seems to be related to #128 #143 #153 but those are already solved.

**Comment by knrybarczyk** [comment]
Yes, you're right I'm using a pretty old version `0.6.18`. This issue was solved when I used the latest version, but I had some other errors from Docker. Since this is a pretty big legacy project I will stick to openjdk 10 for now. Thanks for your support @augi, I guess we can close this issue.
