### ISSUE TITLE
useComposeFiles val cannot be reassigned in 0.14.9

### ISSUE THREAD

**Issue by withzombies** [avast/gradle-docker-compose-plugin#315]
Hello, I tried upgrading to 0.1.4.9 and it does not like the way we're assigning useComposeFiles:

```kotlin
dockerCompose {
    projectName = "ivy"
    useComposeFiles = listOf(project(":server:databases:ivy").file("docker-compose.yml").path)
}
```

```
org.gradle.internal.exceptions.LocationAwareException: Build file 'server/applications/ivy-seed/build.gradle.kts' line: 41
Script compilation errors:

  Line 41:     useComposeFiles = listOf(project(":server:databases:ivy").file("docker-compose.yml").path)
               ^ Val cannot be reassigned

  Line 41:     useComposeFiles = listOf(project(":server:databases:ivy").file("docker-compose.yml").path)
                                 ^ Type mismatch: inferred type is List<String!> but ListProperty<String!>! was expected

  Line 41:     useComposeFiles = listOf(project(":server:databases:ivy").file("docker-compose.yml").path)
                                 ^ Type mismatch: inferred type is List<String!> but ListProperty<String!>! was expected

  Line 42:     useComposeFiles.add(0, )
                               ^ None of the following functions can be called with the arguments supplied: 
                                   public abstract fun add(p0: String!): Unit defined in org.gradle.api.provider.ListProperty
                                   public abstract fun add(p0: Provider<out String!>!): Unit defined in org.gradle.api.provider.ListProperty
```

It seems like the change was introduced here (ce817954) but the documentation wasn't updated to reflect the new method

**Comment by augi** [comment]
Hello, thank you for reporting the issue, and sorry for the inconvenience 😢 

Unfortunately, I have zero experience with Kotlin Gradle DSL so I don't how the syntax should look like. Do you please have any idea? 🙏 

My guess is that Kotlin is more strict (speaking about type-safety) and so you have to call `useComposeFiles.set(listOf(...))` instead. Could you please verify this? 🙏

**Comment by dinomite** [comment]
I see this with various properties of the `dockerCompose` block in my Kotlin build script trying to upgrade from 0.14.5 to 0.14.9.

@augi `….set(listOf(...))` does not work, nor does `set…(listOf())`. The context is that Kotlin transparently allows accessing setters (e.g. `setFoo()`) via assignment (e.g. `foo = …`) and in Gradle build scripts the use of assignment is required.

Glancing at recent changesets, I think the rearchitecture of [`ComposeSettings.groovy'](https://github.com/avast/gradle-docker-compose-plugin/pull/311/files#diff-020fd30d73c7f29bfeaf52eac8acc2ae239d9fc7d2bf0ecb980f9e981538b430) is the root of the troubles for us Kotlin buildscript users.

**Comment by augi** [comment]
Yes, all similar issues are due to those changes, but those changes are required to keep the plugin working in future versions of Gradle. In other words, the plugin has used a legacy way of declaring properties so far. Now, the plugin declares its properties in the right way.

I have zero experience with Kotlin DSL so I marked this issue with `help wanted` and hopefully someone is able to say how to set those properties correctly 🙏 

I've checked the documentation and [ListProperty](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ListProperty.html) has [set method that accepts java.lang.Iterable](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/HasMultipleValues.html#set-java.lang.Iterable-) so maybe the issue is that the Kotlin `listOf` returns an incompatible type? 🤔

**Comment by CristianGM** [comment]
I've just migrated a repo build file from groovy to kts and:
`useComposeFiles.set(listOf("..."))`
worked perfectly

It's the expected kts behavior

**Comment by arhohuttunen** [comment]
I had the same problem and for me the problem was that I had a `com.nike.pdm.localstack` plugin in the same project. This plugin was fetching an older version 0.12.1 of the `gradle-docker-compose` plugin.

The `useComposeFiles.set(listOf("..."))` works with the newer version of the plugin, so your issue might be a transitive dependency.
