### ISSUE TITLE
Custom project name not used since 0.16.0

### ISSUE THREAD

**Issue by robertfmurdock** [avast/gradle-docker-compose-plugin#354]
I've only had a few minutes to look at it, but looks like the customer project names aren't working with the 1.6.0 version. It appears to always use generated names now.

**Comment by augi** [comment]
So the issue is between 0.15.x and 0.16.x versions of this plugin, right?

**Comment by robertfmurdock** [comment]
First noticed it with the 16.0 release

**Comment by augi** [comment]
Sorry for the inconvenience. The problem was that the `String` value of the `projectName` was immediately copied (so before you assigned it a new value), so a value assigned later wasn't taken into account. The fix is refactoring the property from a plain `String` to `Provider<String>`. I've also added a test that checks this feature is working properly.

**Comment by bellini-ea** [comment]
Does the main documentation README.MD need to be updated based on this?  I've been trying to upgrade to 0.16.3 from 0.16.2 and having issues setting the projectName.  I'm also using the Kotlin DSL.

**Comment by augi** [comment]
Hello, thank you for reporting this. I've just tried to address this issue in [this commit](https://github.com/avast/gradle-docker-compose-plugin/commit/a6afb552f505ed1efcbcc28bea9a7bc2bd88a86c)
