### ISSUE TITLE
Is this the correct way to call composeDown twice?

### ISSUE THREAD

**Issue by ericfrancis** [avast/gradle-docker-compose-plugin#74]
```
task finalComposeDown(type: com.avast.gradle.dockercompose.tasks.ComposeDown) {
  extension = new ComposeExtension(project, composeUp, composeDown)
}

integrationTest {
  dependsOn composeDown, composeUp
  finalizedBy finalComposeDown
}
```

I'm new to gradle. Trying to make sure that a mysql container is freshly created before running the integrationTests.

Is there a better way to do this?

**Comment by andrcuns** [comment]
What would be the use case? I think all You would usually need is `dependsOn composeUp` and `finalizedBy composeDown` and that's it. Or use `dockerCompose.isRequiredBy(integrationTest)`. While there might be the cases where some container might be left running due to some manual mocking around and subsequent run might fail because composeUp might not work properly, it shouldn't happen in normal situation, containers are removed during composeDown and new one is created on next run.

**Comment by augi** [comment]
Exactly as @andrcuns wrote - use `dependsOn` and `finalizeBy` manually, or `dockerCompose.isRequiredBy(integrationTest)` as described in `README`.

**Comment by ericfrancis** [comment]
In my case, it is common to have the mysql service running already. 

Running `./gradlew composeUp` twice will create the mysql service on the first call, and then assert that it is still running on the second call.

Calling `composeDown` makes sure that the container is destroyed and then recreated.

Can you pass parameters to `composeUp` to force recreating containers?

**Comment by augi** [comment]
So you are requesting usage of `--force-recreate` when calling `docker-compose up`? Is it correct?

**Comment by ericfrancis** [comment]
Ah, yes. That would be great! Did not know that existed.

**Comment by augi** [comment]
I added `forceRecreate` property to the extension - it's in `0.5.1`. Please note that I had to change name of the plugin so you must also update name of dependency.
